### PR TITLE
rmw_fastrtps_cpp report 2021

### PR DESCRIPTION
**Pull request by IkerLuengo**
As part of the process for choosing the default RMW implementation for ROS2 Humble, this pull request delivers the report prepared by eProsima for rmw_fastrtps_cpp as requested by the TSC.

### CODE REVIEW

**Comment by clalancette** [comment]
@IkerLuengo Thanks for the PR!  I'll take a look and provide some feedback.

**Review by clalancette — COMMENTED** [review]
Overall, looking pretty good.  The only feedback I have here is about the formatting.  Please move your entire response to a new file, something like `eProsima-response.md`, and then link to it from the README.md.  That way we keep the current contents of the README.md.

**Comment by IkerLuengo** [comment]
Thanks for the comments, @clalancette 
Although it was probably not necessary, I rewrote the branch history to keep the history of the README cleaner.

**Comment by clalancette** [comment]
> Although it was probably not necessary, I rewrote the branch history to keep the history of the README cleaner.

Thanks, appreciated.

**Comment by clalancette** [comment]
@IkerLuengo This looks good, thanks for updating the PR.

I'm going to go ahead and merge this as-is, and then start an editing pass.  While editing, we'll mostly be doing things like fixing proper names (`ROS2` -> `ROS 2`, `cycloneDDS -> Cyclone DDS`), and any small typos we see.  We won't change the content in any substantial way.  We'll be doing this through pull requests, so you should be able to see the changes we are making.  Let us know if you have any questions about this.

**Pull request merged**
